import type { QueryBase } from './types';

export const queryKeys = {
  dashboardOverview: (filters: QueryBase = {}) => ['analytics-overview', filters] as const,
  users: (filters: QueryBase = {}) => ['users', filters] as const,
  settingsCampuses: (filters: QueryBase = {}) => ['settings-campuses', filters] as const,
  settingsTerms: (filters: QueryBase = {}) => ['settings-terms', filters] as const,
  settingsDictionaries: (filters: QueryBase = {}) => ['settings-dictionaries', filters] as const,
  jobs: (filters: QueryBase = {}) => ['jobs', filters] as const,
  teachers: (filters: QueryBase = {}) => ['teachers', filters] as const,
  teacherDetail: (teacherId: string) => ['teacher-detail', teacherId] as const,
  students: (filters: QueryBase = {}) => ['students', filters] as const,
  studentDetail: (studentId: string) => ['student-detail', studentId] as const,
  families: (filters: QueryBase = {}) => ['families', filters] as const,
  familyDetail: (familyId: string) => ['family-detail', familyId] as const,
  homeworkSubmissions: (filters: QueryBase & { subject?: string; teacherId?: string; aiStatus?: string; reviewStatus?: string; dateFrom?: string; dateTo?: string } = {}) => ['homework-submissions', filters] as const,
  homeworkSubmissionDetail: (submissionId: string) => ['homework-submission-detail', submissionId] as const,
  homeworkReviewDraft: (submissionId: string) => ['homework-review-draft', submissionId] as const,
  homeworkErrorTaxonomies: (filters: QueryBase = {}) => ['homework-error-taxonomies', filters] as const,
  growthRubrics: (filters: QueryBase = {}) => ['growth-rubrics', filters] as const,
  growthRubricDetail: (rubricId: string) => ['growth-rubric-detail', rubricId] as const,
  growthObservations: (filters: QueryBase & { studentId?: string; teacherId?: string; dateFrom?: string; dateTo?: string; scene?: string; reportPublished?: string } = {}) => ['growth-observations', filters] as const,
  growthGoals: (filters: QueryBase & { studentId?: string; teacherId?: string } = {}) => ['growth-goals', filters] as const,
  growthGoalDetail: (goalId: string) => ['growth-goal-detail', goalId] as const,
  growthReports: (filters: QueryBase & { reportType?: string; publishStatus?: string } = {}) => ['growth-reports', filters] as const,
  attendanceBoard: (filters: QueryBase & { date?: string; eventType?: string } = {}) => ['attendance-board', filters] as const,
  attendanceDevices: (filters: QueryBase & { tab?: string; deviceType?: string } = {}) => ['attendance-devices', filters] as const,
  attendanceDeviceBindings: (filters: QueryBase & { tab?: string } = {}) => ['attendance-device-bindings', filters] as const,
  attendanceHomeworkTime: (filters: QueryBase & { studentId?: string; subject?: string; dateFrom?: string; dateTo?: string } = {}) => ['attendance-homework-time', filters] as const,
  billingProducts: (filters: QueryBase = {}) => ['billing-products', filters] as const,
  billingContracts: (filters: QueryBase & { familyId?: string; studentId?: string; teacherId?: string; endDateFrom?: string; endDateTo?: string } = {}) => ['billing-contracts', filters] as const,
  billingInvoices: (filters: QueryBase & { familyId?: string; studentId?: string; dueDateFrom?: string; dueDateTo?: string; tab?: string } = {}) => ['billing-invoices', filters] as const,
  billingRenewals: (filters: QueryBase & { familyId?: string; studentId?: string; ownerId?: string } = {}) => ['billing-renewals', filters] as const,
  communicationRecords: (filters: QueryBase & { familyId?: string; studentId?: string; channel?: string; direction?: string; dateFrom?: string; dateTo?: string } = {}) => ['communication-records', filters] as const,
  communicationMessages: (filters: QueryBase & { familyId?: string; studentId?: string; channel?: string; messageStatus?: string; dateFrom?: string; dateTo?: string } = {}) => ['communication-messages', filters] as const,
};
